[package]
name = "rust-gamejam"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", features = [
    "bevy_gilrs",
    "bevy_winit",
    "render",
    "png",
    "hdr",
    "vorbis",
    "x11",
    "filesystem_watcher",
    "trace"
     ] }
bevy-inspector-egui = "0.11"
bevy_asset_loader = { version = "0.11", features = ["2d"] }

[features]
default = ["fast-compile"]
fast-compile = ["bevy/dynamic"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
