name: validate_rust
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Rust Nightly (2022-05-15)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-05-15
          override: true
          profile: minimal
          components: rustfmt
      - name: cargo fmt check
        run: cargo fmt --check

  validate:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: cargo clippy check
        run: cargo clippy -- -D warnings
      - name: cargo test
        run: cargo test
